### ISSUE TITLE
setting php.ini options fails

### ISSUE THREAD

**Issue by gesinn-it-gea** [robertdebock/ansible-role-php#6]
## Describe the bug
It seems, that setting php.ini options is not working as expected. For example, the default for `php_max_execution_time` is set to `60` in `defaults/main.yml`. In fact `/etc/php/7.3/apache2/php.ini` on a Debian guest show `max_execution_time = 30`.

## Playbook

I tried setting `php_max_execution_time` in a playbook either as playbook var or as role var, which seems to be ignored, too:

**via playbook var**
```yaml
---
  vars:
    # robertdebock.openssl
    openssl_items:
      - name: apache-httpd
        common_name: "{{ ansible_fqdn }}"

    # robertdebock.httpd
    httpd_vhosts:
      - name: mediawiki
        servername: localhost
        documentroot: /var/www/localhost/mediawiki
    _httpd_config_directory:
      Debian: "{{ httpd_server_root }}/sites-enabled"

    # robertdebock.php
    php_max_execution_time: 240     # required to avoid timeout on first scss compilation (Chameleon skin)

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd
    - role: robertdebock.php
```

**via role var**
```yaml
---
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd
    - role: robertdebock.php
      vars:
        php_max_execution_time: 240
```

## Output

Show at least the error, possible related output, maybe just all the output.

## Environment

- Debian 10
- Ansible 2.10.7

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
