### ISSUE TITLE
set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by SFTP-ChZeman** [robertdebock/ansible-role-php#7]
# Describe the bug

Installing PHP fails (on both the control node and managed node) at "Find used php.ini" with error message "stderr: '/bin/sh: 1: set: Illegal option -o pipefail'"

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: Install LAMP Packages
  hosts: all
  roles:
    - robertdebock.httpd
    - robertdebock.mysql
    - robertdebock.php
    - robertdebock.phpmyadmin
  become: true
```

## Output

11:17:37 AM     TASK [robertdebock.php : Find used php.ini] ************************************
11:17:38 AM     fatal: [10.0.5.100]: FAILED! => changed=false
11:17:38 AM     cmd: set -o pipefail && php -r 'phpinfo();' | grep 'Loaded Configuration File' | awk '{ print $NF }'
11:17:38 AM     delta: '0:00:00.010208'
11:17:38 AM     end: '2023-12-29 11:17:38.654760'
11:17:38 AM     msg: non-zero return code
11:17:38 AM     rc: 2
11:17:38 AM     start: '2023-12-29 11:17:38.644552'
11:17:38 AM     stderr: '/bin/sh: 1: set: Illegal option -o pipefail'
11:17:38 AM     stderr_lines:
11:17:38 AM     stdout: ''
11:17:38 AM     stdout_lines: 

## Environment

- Control node OS: Debian 12
- Control node Ansible version: 2.15.8
- Managed node OS: Debian 11

## Fix:
Add the following to tasks/main.yml after cmd: "set -o pipefail && {{ php_ini_command }}":
  args:
    executable: /bin/bash

This fix works because ansible is using /bin/sh instead of /bin/bash.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
